### ISSUE TITLE
Idea on supporting dynamic row height ? 

### ISSUE THREAD

**Issue by Chris2137** [UttamPanchasara/customtablewidget#1]
Hello Sir,

  Thanks for your video and it is great. Just one question. As Flutter official DataTable now supports dynamic height already, do you have any idea on how could the same be possibly achieved if content height is not fixed? 

Thanks again.

**Comment by UttamPanchasara** [comment]
@Chris2137 

Sorry for the delay in response, As with current implementation i have taken fixed height but you can try using `IntrinsicHeight` widget or container with constraint by setting min max height of widget, but i still doubt if that work or not as having dynamic height inside the scrollable widget is difficult.

Thanks
